#Change the default prompt format
format = """\
[╭╴](#56b6c2)$env_var\
$all[╰─](#56b6c2)$character"""
# 
# Change the default prompt characters
[character]
success_symbol = "[](#56b6c2)"
error_symbol = "[](#56b6c2)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "[$path]($style)[$read_only]($read_only_style) "

[python]
format = "[ $version]($style) "
style = "bold green"
